/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import ux.Login;

/**
 *
 * 
 */
        
public class JP001_S1_AFP extends javax.swing.JPanel {
    
    private Login controlador;
    
    public JButton getBtn2_JF001_S1_AF() {
        return Btn2_JF001_S1_AF;
    }
    
    public JButton getbtn3_JF001_S1_AF() {
        return btn3_JF001_S1_AF;
    }

    public JTextField getTxtUsuario_JF001_S1_AF() {
        return TxtUsuario_JF001_S1_AF;
    }

    public JPasswordField getPass_JF001_S1_AF() {
        return Pass_JF001_S1_AF;
    }
    public JButton getbtn4_JF001_S1_AF() {
        return btn4_JF001_S1_AF;
    }
    
    /**
     * Creates new form JP001_S1_AFP
     */
    public JP001_S1_AFP(Login controlador) {
        this.controlador = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP001_S1_AF = new javax.swing.JPanel();
        TxtUsuario_JF001_S1_AF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Btn2_JF001_S1_AF = new javax.swing.JButton();
        btn4_JF001_S1_AF = new javax.swing.JButton();
        btn3_JF001_S1_AF = new javax.swing.JButton();
        Pass_JF001_S1_AF = new javax.swing.JPasswordField();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1120, 540));
        setLayout(new java.awt.CardLayout());

        JP001_S1_AF.setBackground(new java.awt.Color(255, 255, 255));
        JP001_S1_AF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102)));
        JP001_S1_AF.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        JP001_S1_AF.setMaximumSize(new java.awt.Dimension(1120, 540));
        JP001_S1_AF.setMinimumSize(new java.awt.Dimension(1120, 540));
        JP001_S1_AF.setPreferredSize(new java.awt.Dimension(1120, 540));
        JP001_S1_AF.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtUsuario_JF001_S1_AF.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        TxtUsuario_JF001_S1_AF.setForeground(new java.awt.Color(204, 204, 204));
        TxtUsuario_JF001_S1_AF.setText("Usuario");
        TxtUsuario_JF001_S1_AF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        TxtUsuario_JF001_S1_AF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TxtUsuario_JF001_S1_AF.setSelectionColor(new java.awt.Color(0, 0, 0));
        TxtUsuario_JF001_S1_AF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtUsuario_JF001_S1_AFMousePressed(evt);
            }
        });
        TxtUsuario_JF001_S1_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuario_JF001_S1_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(TxtUsuario_JF001_S1_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 400, 40));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Iniciar Sesión");
        JP001_S1_AF.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 140, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Contraseña");
        JP001_S1_AF.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        Btn2_JF001_S1_AF.setBackground(new java.awt.Color(255, 255, 255));
        Btn2_JF001_S1_AF.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        Btn2_JF001_S1_AF.setForeground(new java.awt.Color(255, 255, 255));
        Btn2_JF001_S1_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnIngresarClari.png"))); // NOI18N
        Btn2_JF001_S1_AF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 50, true));
        Btn2_JF001_S1_AF.setBorderPainted(false);
        Btn2_JF001_S1_AF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn2_JF001_S1_AF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn2_JF001_S1_AFMouseClicked(evt);
            }
        });
        Btn2_JF001_S1_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2_JF001_S1_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(Btn2_JF001_S1_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 220, 40));

        btn4_JF001_S1_AF.setBackground(new java.awt.Color(255, 255, 255));
        btn4_JF001_S1_AF.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btn4_JF001_S1_AF.setForeground(new java.awt.Color(0, 102, 102));
        btn4_JF001_S1_AF.setText("¿Se te ha olvidado la contraseña?");
        btn4_JF001_S1_AF.setBorderPainted(false);
        btn4_JF001_S1_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4_JF001_S1_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(btn4_JF001_S1_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 210, 20));

        btn3_JF001_S1_AF.setBackground(new java.awt.Color(255, 255, 255));
        btn3_JF001_S1_AF.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn3_JF001_S1_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnRegisterAdmin.png"))); // NOI18N
        btn3_JF001_S1_AF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btn3_JF001_S1_AF.setBorderPainted(false);
        btn3_JF001_S1_AF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn3_JF001_S1_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3_JF001_S1_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(btn3_JF001_S1_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, 33));

        Pass_JF001_S1_AF.setForeground(new java.awt.Color(204, 204, 204));
        Pass_JF001_S1_AF.setText("Contraseña");
        Pass_JF001_S1_AF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Pass_JF001_S1_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pass_JF001_S1_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(Pass_JF001_S1_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 400, 40));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("Bienvenido a la experiencia con");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogitoGrande.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(63, 63, 63))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel3)
                .addGap(45, 45, 45)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        JP001_S1_AF.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 490, 650));

        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("“Cuando no somos capaces ya de cambiar una situación, ");
        JP001_S1_AF.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, 30));

        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText(" nos enfrentamos al reto de cambiar nosotros mismos”");
        JP001_S1_AF.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 310, -1));

        add(JP001_S1_AF, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUsuario_JF001_S1_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuario_JF001_S1_AFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuario_JF001_S1_AFActionPerformed

    private void Btn2_JF001_S1_AFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2_JF001_S1_AFMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn2_JF001_S1_AFMouseClicked

    private void Btn2_JF001_S1_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2_JF001_S1_AFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn2_JF001_S1_AFActionPerformed

    private void btn4_JF001_S1_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4_JF001_S1_AFActionPerformed
        
    }//GEN-LAST:event_btn4_JF001_S1_AFActionPerformed

    private void btn3_JF001_S1_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3_JF001_S1_AFActionPerformed

    }//GEN-LAST:event_btn3_JF001_S1_AFActionPerformed

    private void Pass_JF001_S1_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pass_JF001_S1_AFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pass_JF001_S1_AFActionPerformed

    private void TxtUsuario_JF001_S1_AFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtUsuario_JF001_S1_AFMousePressed

    
    }//GEN-LAST:event_TxtUsuario_JF001_S1_AFMousePressed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn2_JF001_S1_AF;
    private javax.swing.JPanel JP001_S1_AF;
    public javax.swing.JPasswordField Pass_JF001_S1_AF;
    public javax.swing.JTextField TxtUsuario_JF001_S1_AF;
    public javax.swing.JButton btn3_JF001_S1_AF;
    private javax.swing.JButton btn4_JF001_S1_AF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}

