/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

/**
 *
 * @author 50369
 */
public class JP005_2_S2_RH extends javax.swing.JPanel {

    /**
     * Creates new form JP005_2_S2_RH
     */
    public JP005_2_S2_RH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JP001_S1_RH = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TxtCodigoTel_JF005_2_S2_RH = new javax.swing.JTextField();
        Btn2_JF005_2_S2_RH = new javax.swing.JButton();
        Btn1_JF005_2_S2_RH = new javax.swing.JButton();
        btn3_JF005_2_S2_RH = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setkGradientFocus(50);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MINDLINK");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 247, 65));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>\nBienvenido a la mejor experiencia\n<br>\n\n\n\n");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        JP001_S1_RH.setBackground(new java.awt.Color(255, 255, 255));
        JP001_S1_RH.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JP001_S1_RH.setForeground(new java.awt.Color(153, 153, 255));
        JP001_S1_RH.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("RECUPERA TU CONTRASEÑA");

        TxtCodigoTel_JF005_2_S2_RH.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        TxtCodigoTel_JF005_2_S2_RH.setForeground(new java.awt.Color(153, 153, 153));
        TxtCodigoTel_JF005_2_S2_RH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtCodigoTel_JF005_2_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtCodigoTel_JF005_2_S2_RH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoTel_JF005_2_S2_RHActionPerformed(evt);
            }
        });

        Btn2_JF005_2_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn2_JF005_2_S2_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Btn2_JF005_2_S2_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn2_JF005_2_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Registrarse2.png"))); // NOI18N
        Btn2_JF005_2_S2_RH.setText("Registrarse");
        Btn2_JF005_2_S2_RH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Btn2_JF005_2_S2_RH.setBorderPainted(false);
        Btn2_JF005_2_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn2_JF005_2_S2_RH.setInheritsPopupMenu(true);

        Btn1_JF005_2_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn1_JF005_2_S2_RH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Btn1_JF005_2_S2_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn1_JF005_2_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnIngresar2.png"))); // NOI18N
        Btn1_JF005_2_S2_RH.setText("Ingresar");
        Btn1_JF005_2_S2_RH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 50, true));
        Btn1_JF005_2_S2_RH.setBorderPainted(false);
        Btn1_JF005_2_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn1_JF005_2_S2_RH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1_JF005_2_S2_RHActionPerformed(evt);
            }
        });

        btn3_JF005_2_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        btn3_JF005_2_S2_RH.setForeground(new java.awt.Color(0, 102, 102));
        btn3_JF005_2_S2_RH.setText("¿Quieres probar otro método de recuperación?");
        btn3_JF005_2_S2_RH.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("<html> Sigue las siguientes indicaciones para recuperar tu contraseña <br>    ");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Ingresa el código enviado al número de teléfono  asociado");

        javax.swing.GroupLayout JP001_S1_RHLayout = new javax.swing.GroupLayout(JP001_S1_RH);
        JP001_S1_RH.setLayout(JP001_S1_RHLayout);
        JP001_S1_RHLayout.setHorizontalGroup(
            JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP001_S1_RHLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP001_S1_RHLayout.createSequentialGroup()
                        .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn3_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(50, 50, 50)))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP001_S1_RHLayout.createSequentialGroup()
                        .addGroup(JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn1_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn2_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP001_S1_RHLayout.createSequentialGroup()
                        .addComponent(TxtCodigoTel_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        JP001_S1_RHLayout.setVerticalGroup(
            JP001_S1_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP001_S1_RHLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(TxtCodigoTel_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Btn1_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn2_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn3_JF005_2_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        kGradientPanel1.add(JP001_S1_RH, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -10, 480, 610));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logitooo 2.png"))); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 370, 180));

        add(kGradientPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodigoTel_JF005_2_S2_RHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoTel_JF005_2_S2_RHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoTel_JF005_2_S2_RHActionPerformed

    private void Btn1_JF005_2_S2_RHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1_JF005_2_S2_RHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn1_JF005_2_S2_RHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn1_JF005_2_S2_RH;
    public javax.swing.JButton Btn2_JF005_2_S2_RH;
    public javax.swing.JPanel JP001_S1_RH;
    public javax.swing.JTextField TxtCodigoTel_JF005_2_S2_RH;
    private javax.swing.JButton btn3_JF005_2_S2_RH;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
