/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import ux.Abrirvistas;

/**
 *
 * @author 50369
 */
public class JP004_S2_AF extends javax.swing.JPanel {

    /**
     * Creates new form JP004_S2_AF
     */
    public JP004_S2_AF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP001_S1_AF = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn01_JF005_S2_AF = new javax.swing.JButton();
        btn02_JF005_S2_AF = new javax.swing.JButton();
        btn03_JF005_S2_AF = new javax.swing.JButton();
        btn04_JF005_S2_AF = new javax.swing.JButton();
        btn05_JF005_S2_AF = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn06_JF005_S2_AF = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        JP001_S1_AF.setBackground(new java.awt.Color(255, 255, 255));
        JP001_S1_AF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 102, 102)));
        JP001_S1_AF.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        JP001_S1_AF.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("¿Qué desea realizar hoy administrador?");
        JP001_S1_AF.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jPanel1.setBackground(new java.awt.Color(44, 102, 110));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        JP001_S1_AF.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        btn01_JF005_S2_AF.setBackground(new java.awt.Color(255, 255, 255));
        btn01_JF005_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnPersonal.png"))); // NOI18N
        btn01_JF005_S2_AF.setBorderPainted(false);
        btn01_JF005_S2_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01_JF005_S2_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(btn01_JF005_S2_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 150, 180));

        btn02_JF005_S2_AF.setBackground(new java.awt.Color(255, 255, 255));
        btn02_JF005_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEstadisticas.png"))); // NOI18N
        btn02_JF005_S2_AF.setBorderPainted(false);
        btn02_JF005_S2_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02_JF005_S2_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(btn02_JF005_S2_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 150, 180));

        btn03_JF005_S2_AF.setBackground(new java.awt.Color(255, 255, 255));
        btn03_JF005_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAnuncios.png"))); // NOI18N
        btn03_JF005_S2_AF.setBorderPainted(false);
        btn03_JF005_S2_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn03_JF005_S2_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(btn03_JF005_S2_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 150, 180));

        btn04_JF005_S2_AF.setBackground(new java.awt.Color(255, 255, 255));
        btn04_JF005_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnAcercaDClinic.png"))); // NOI18N
        btn04_JF005_S2_AF.setBorderPainted(false);
        btn04_JF005_S2_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn04_JF005_S2_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(btn04_JF005_S2_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 170, 180));

        btn05_JF005_S2_AF.setBackground(new java.awt.Color(255, 255, 255));
        btn05_JF005_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnComents.png"))); // NOI18N
        btn05_JF005_S2_AF.setBorderPainted(false);
        btn05_JF005_S2_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn05_JF005_S2_AFActionPerformed(evt);
            }
        });
        JP001_S1_AF.add(btn05_JF005_S2_AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 160, 180));

        jPanel3.setBackground(new java.awt.Color(200, 232, 232));

        btn06_JF005_S2_AF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cssa.PNG"))); // NOI18N
        btn06_JF005_S2_AF.setText("jButton6");
        btn06_JF005_S2_AF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn06_JF005_S2_AFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addComponent(btn06_JF005_S2_AF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(364, 364, 364))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn06_JF005_S2_AF, javax.swing.GroupLayout.PREFERRED_SIZE, 90, Short.MAX_VALUE)
        );

        JP001_S1_AF.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 900, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        JP001_S1_AF.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 170, 90));

        add(JP001_S1_AF, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn01_JF005_S2_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01_JF005_S2_AFActionPerformed
        Abrirvistas.abrir("JF008_S2_AF");
    }//GEN-LAST:event_btn01_JF005_S2_AFActionPerformed

    private void btn02_JF005_S2_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02_JF005_S2_AFActionPerformed
        Abrirvistas.abrir("JF022_S3_AF");
    }//GEN-LAST:event_btn02_JF005_S2_AFActionPerformed

    private void btn03_JF005_S2_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn03_JF005_S2_AFActionPerformed
        Abrirvistas.abrir("JF006_S2_AF");
    }//GEN-LAST:event_btn03_JF005_S2_AFActionPerformed

    private void btn04_JF005_S2_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn04_JF005_S2_AFActionPerformed
        Abrirvistas.abrir("JF013_S2_RH");
    }//GEN-LAST:event_btn04_JF005_S2_AFActionPerformed

    private void btn05_JF005_S2_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn05_JF005_S2_AFActionPerformed

        Abrirvistas.abrir("JF007_S2_RH");
    }//GEN-LAST:event_btn05_JF005_S2_AFActionPerformed

    private void btn06_JF005_S2_AFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn06_JF005_S2_AFActionPerformed

        Abrirvistas.abrir("JF008_S2_AF");
    }//GEN-LAST:event_btn06_JF005_S2_AFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel JP001_S1_AF;
    public javax.swing.JButton btn01_JF005_S2_AF;
    public javax.swing.JButton btn02_JF005_S2_AF;
    public javax.swing.JButton btn03_JF005_S2_AF;
    public javax.swing.JButton btn04_JF005_S2_AF;
    public javax.swing.JButton btn05_JF005_S2_AF;
    public javax.swing.JButton btn06_JF005_S2_AF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
