/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import ux.PanelesInicializador;
import ux.VerSolicitudAprobada;

/**
 *
 * @author LENOVO
 */
public class JP017_1_S2_RH extends javax.swing.JPanel {

    private VerSolicitudAprobada controlador;
    private PanelesInicializador str;

    public JButton getBtn1_JF017_S2_RH() {
        return Btn1_JF017_S2_RH;
    }

    public void setBtn1_JF017_S2_RH(JButton Btn1_JF017_S2_RH) {
        this.Btn1_JF017_S2_RH = Btn1_JF017_S2_RH;
    }

    public JButton getBtn1_JF017_S2_RH1() {
        return Btn1_JF017_S2_RH1;
    }

    public void setBtn1_JF017_S2_RH1(JButton Btn1_JF017_S2_RH1) {
        this.Btn1_JF017_S2_RH1 = Btn1_JF017_S2_RH1;
    }

    public JButton getBtn2_JF017_S2_RH1() {
        return Btn2_JF017_S2_RH1;
    }

    public void setBtn2_JF017_S2_RH1(JButton Btn2_JF017_S2_RH1) {
        this.Btn2_JF017_S2_RH1 = Btn2_JF017_S2_RH1;
    }

    public JPanel getJPSolicitud_JP017_S2_RH1() {
        return JPSolicitud_JP017_S2_RH1;
    }

    public void setJPSolicitud_JP017_S2_RH1(JPanel JPSolicitud_JP017_S2_RH1) {
        this.JPSolicitud_JP017_S2_RH1 = JPSolicitud_JP017_S2_RH1;
    }

    public JLabel getJlLogo() {
        return JlLogo;
    }

    public void setJlLogo(JLabel JlLogo) {
        this.JlLogo = JlLogo;
    }

    public JLabel getJlLogo1() {
        return JlLogo1;
    }

    public void setJlLogo1(JLabel JlLogo1) {
        this.JlLogo1 = JlLogo1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return LblAsunto;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.LblAsunto = jLabel2;
    }

    public JTextArea getLbNotas() {
        return LbNotas;
    }

    public void setLbNotasText(String texto) {
        this.LbNotas.setText(texto);
    }

    public JLabel getLblAsunto() {
        return LblAsunto;
    }

    public void setLblAsunto(String LblAsunto) {
        this.LblAsunto.setText(LblAsunto);
    }

    public JP017_1_S2_RH(VerSolicitudAprobada controlador) {
        initComponents();
        this.controlador = controlador;

        str = new PanelesInicializador();

        // Establecer el valor de str aquí después de haberlo creado
        str.setJP017_1_S2_RH(this);
    }

    public JP017_1_S2_RH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn1_JF017_S2_RH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JlLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Btn1_JF017_S2_RH1 = new javax.swing.JButton();
        JlLogo1 = new javax.swing.JLabel();
        JPSolicitud_JP017_S2_RH1 = new javax.swing.JPanel();
        Btn2_JF017_S2_RH1 = new javax.swing.JButton();
        LblAsunto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LbNotas = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1120, 640));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 640));

        Btn1_JF017_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn1_JF017_S2_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn1_JF017_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector (1).png"))); // NOI18N
        Btn1_JF017_S2_RH.setBorderPainted(false);
        Btn1_JF017_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Esta solicitud la aprobaste");

        JlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Btn1_JF017_S2_RH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(273, 273, 273)
                .addComponent(JlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn1_JF017_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(JlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(538, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");

        jPanel2.setMaximumSize(new java.awt.Dimension(1120, 640));
        jPanel2.setMinimumSize(new java.awt.Dimension(1120, 640));
        jPanel2.setPreferredSize(new java.awt.Dimension(1120, 640));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Btn1_JF017_S2_RH1.setBackground(new java.awt.Color(255, 255, 255));
        Btn1_JF017_S2_RH1.setForeground(new java.awt.Color(255, 255, 255));
        Btn1_JF017_S2_RH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector (1).png"))); // NOI18N
        Btn1_JF017_S2_RH1.setBorderPainted(false);
        Btn1_JF017_S2_RH1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        JlLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N

        JPSolicitud_JP017_S2_RH1.setBackground(new java.awt.Color(246, 246, 246));
        JPSolicitud_JP017_S2_RH1.setMaximumSize(new java.awt.Dimension(1120, 540));

        Btn2_JF017_S2_RH1.setBackground(new java.awt.Color(246, 246, 246));
        Btn2_JF017_S2_RH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rechazarS.png"))); // NOI18N
        Btn2_JF017_S2_RH1.setBorderPainted(false);
        Btn2_JF017_S2_RH1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LblAsunto.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        LblAsunto.setText("Asunto");

        LbNotas.setBackground(new java.awt.Color(255, 255, 255));
        LbNotas.setColumns(20);
        LbNotas.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LbNotas.setForeground(new java.awt.Color(51, 51, 51));
        LbNotas.setRows(5);
        LbNotas.setText("Contenido");
        LbNotas.setBorder(null);
        LbNotas.setCaretColor(new java.awt.Color(255, 255, 255));
        LbNotas.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(LbNotas);

        javax.swing.GroupLayout JPSolicitud_JP017_S2_RH1Layout = new javax.swing.GroupLayout(JPSolicitud_JP017_S2_RH1);
        JPSolicitud_JP017_S2_RH1.setLayout(JPSolicitud_JP017_S2_RH1Layout);
        JPSolicitud_JP017_S2_RH1Layout.setHorizontalGroup(
            JPSolicitud_JP017_S2_RH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                .addGroup(JPSolicitud_JP017_S2_RH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(Btn2_JF017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblAsunto)))
                .addContainerGap(293, Short.MAX_VALUE))
            .addGroup(JPSolicitud_JP017_S2_RH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(37, Short.MAX_VALUE)))
        );
        JPSolicitud_JP017_S2_RH1Layout.setVerticalGroup(
            JPSolicitud_JP017_S2_RH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblAsunto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(Btn2_JF017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(JPSolicitud_JP017_S2_RH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(108, Short.MAX_VALUE)))
        );

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("Esta solicitud la aprobaste");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Btn1_JF017_S2_RH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JlLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(JPSolicitud_JP017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(415, 415, 415)
                    .addComponent(jLabel3)
                    .addContainerGap(445, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn1_JF017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JlLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(JPSolicitud_JP017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jLabel3)
                    .addContainerGap(528, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel3, "card2");

        add(jPanel2, "card3");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn1_JF017_S2_RH;
    public javax.swing.JButton Btn1_JF017_S2_RH1;
    public javax.swing.JButton Btn2_JF017_S2_RH1;
    public javax.swing.JPanel JPSolicitud_JP017_S2_RH1;
    public javax.swing.JLabel JlLogo;
    public javax.swing.JLabel JlLogo1;
    public javax.swing.JTextArea LbNotas;
    public javax.swing.JLabel LblAsunto;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
