/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import ux.PanelesInicializador;
import ux.VerSolicitudAprobada;

/**
 *
 * @author LENOVO
 */
public class JP017_1_S2_RH extends javax.swing.JPanel {

   private VerSolicitudAprobada controlador;
    private PanelesInicializador str;

    public JButton getBtn1_JF017_S2_RH() {
        return Btn1_JF017_S2_RH;
    }

    public void setBtn1_JF017_S2_RH(JButton Btn1_JF017_S2_RH) {
        this.Btn1_JF017_S2_RH = Btn1_JF017_S2_RH;
    }

    public JButton getBtn1_JF017_S2_RH1() {
        return Btn1_JF017_S2_RH1;
    }

    public void setBtn1_JF017_S2_RH1(JButton Btn1_JF017_S2_RH1) {
        this.Btn1_JF017_S2_RH1 = Btn1_JF017_S2_RH1;
    }

    public JButton getBtn2_JF017_S2_RH() {
        return Btn2_JF017_S2_RH;
    }

    public void setBtn2_JF017_S2_RH(JButton Btn2_JF017_S2_RH) {
        this.Btn2_JF017_S2_RH = Btn2_JF017_S2_RH;
    }

    public JButton getBtn2_JF017_S2_RH1() {
        return Btn2_JF017_S2_RH1;
    }

    public void setBtn2_JF017_S2_RH1(JButton Btn2_JF017_S2_RH1) {
        this.Btn2_JF017_S2_RH1 = Btn2_JF017_S2_RH1;
    }

    public JPanel getJPSolicitud_JP017_S2_RH() {
        return JPSolicitud_JP017_S2_RH;
    }

    public void setJPSolicitud_JP017_S2_RH(JPanel JPSolicitud_JP017_S2_RH) {
        this.JPSolicitud_JP017_S2_RH = JPSolicitud_JP017_S2_RH;
    }

    public JPanel getJPSolicitud_JP017_S2_RH1() {
        return JPSolicitud_JP017_S2_RH1;
    }

    public void setJPSolicitud_JP017_S2_RH1(JPanel JPSolicitud_JP017_S2_RH1) {
        this.JPSolicitud_JP017_S2_RH1 = JPSolicitud_JP017_S2_RH1;
    }

    public JLabel getJlLogo() {
        return JlLogo;
    }

    public void setJlLogo(JLabel JlLogo) {
        this.JlLogo = JlLogo;
    }

    public JLabel getJlLogo1() {
        return JlLogo1;
    }

    public void setJlLogo1(JLabel JlLogo1) {
        this.JlLogo1 = JlLogo1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }
    
    
    
    
    

    public JP017_1_S2_RH(VerSolicitudAprobada controlador) {
        initComponents();
        this.controlador = controlador;
        
        str = new PanelesInicializador();
        
         // Establecer el valor de str aquí después de haberlo creado
        str.setJP017_1_S2_RH(this);
    }
    public JP017_1_S2_RH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn1_JF017_S2_RH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JlLogo = new javax.swing.JLabel();
        JPSolicitud_JP017_S2_RH = new javax.swing.JPanel();
        Btn2_JF017_S2_RH = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Btn1_JF017_S2_RH1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JlLogo1 = new javax.swing.JLabel();
        JPSolicitud_JP017_S2_RH1 = new javax.swing.JPanel();
        Btn2_JF017_S2_RH1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1120, 640));
        setMinimumSize(new java.awt.Dimension(1120, 640));
        setPreferredSize(new java.awt.Dimension(1120, 640));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1120, 640));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(1120, 640));

        Btn1_JF017_S2_RH.setBackground(new java.awt.Color(255, 255, 255));
        Btn1_JF017_S2_RH.setForeground(new java.awt.Color(255, 255, 255));
        Btn1_JF017_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector (1).png"))); // NOI18N
        Btn1_JF017_S2_RH.setBorderPainted(false);
        Btn1_JF017_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Esta solicitud la aprobaste");

        JlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N

        JPSolicitud_JP017_S2_RH.setBackground(new java.awt.Color(246, 246, 246));
        JPSolicitud_JP017_S2_RH.setMaximumSize(new java.awt.Dimension(1120, 540));

        Btn2_JF017_S2_RH.setBackground(new java.awt.Color(246, 246, 246));
        Btn2_JF017_S2_RH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rechazarS.png"))); // NOI18N
        Btn2_JF017_S2_RH.setBorderPainted(false);
        Btn2_JF017_S2_RH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPSolicitud_JP017_S2_RHLayout = new javax.swing.GroupLayout(JPSolicitud_JP017_S2_RH);
        JPSolicitud_JP017_S2_RH.setLayout(JPSolicitud_JP017_S2_RHLayout);
        JPSolicitud_JP017_S2_RHLayout.setHorizontalGroup(
            JPSolicitud_JP017_S2_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSolicitud_JP017_S2_RHLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(Btn2_JF017_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        JPSolicitud_JP017_S2_RHLayout.setVerticalGroup(
            JPSolicitud_JP017_S2_RHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPSolicitud_JP017_S2_RHLayout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addComponent(Btn2_JF017_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Btn1_JF017_S2_RH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(273, 273, 273)
                .addComponent(JlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(JPSolicitud_JP017_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn1_JF017_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(JlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addComponent(JPSolicitud_JP017_S2_RH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");

        jPanel2.setMaximumSize(new java.awt.Dimension(1120, 640));
        jPanel2.setMinimumSize(new java.awt.Dimension(1120, 640));
        jPanel2.setPreferredSize(new java.awt.Dimension(1120, 640));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Btn1_JF017_S2_RH1.setBackground(new java.awt.Color(255, 255, 255));
        Btn1_JF017_S2_RH1.setForeground(new java.awt.Color(255, 255, 255));
        Btn1_JF017_S2_RH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Vector (1).png"))); // NOI18N
        Btn1_JF017_S2_RH1.setBorderPainted(false);
        Btn1_JF017_S2_RH1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Esta solicitud la aprobaste");

        JlLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/log.PNG"))); // NOI18N

        JPSolicitud_JP017_S2_RH1.setBackground(new java.awt.Color(246, 246, 246));
        JPSolicitud_JP017_S2_RH1.setMaximumSize(new java.awt.Dimension(1120, 540));

        Btn2_JF017_S2_RH1.setBackground(new java.awt.Color(246, 246, 246));
        Btn2_JF017_S2_RH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rechazarS.png"))); // NOI18N
        Btn2_JF017_S2_RH1.setBorderPainted(false);
        Btn2_JF017_S2_RH1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPSolicitud_JP017_S2_RH1Layout = new javax.swing.GroupLayout(JPSolicitud_JP017_S2_RH1);
        JPSolicitud_JP017_S2_RH1.setLayout(JPSolicitud_JP017_S2_RH1Layout);
        JPSolicitud_JP017_S2_RH1Layout.setHorizontalGroup(
            JPSolicitud_JP017_S2_RH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(Btn2_JF017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        JPSolicitud_JP017_S2_RH1Layout.setVerticalGroup(
            JPSolicitud_JP017_S2_RH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPSolicitud_JP017_S2_RH1Layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addComponent(Btn2_JF017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Btn1_JF017_S2_RH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(273, 273, 273)
                .addComponent(JlLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(JPSolicitud_JP017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn1_JF017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(JlLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addComponent(JPSolicitud_JP017_S2_RH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, "card2");

        add(jPanel2, "card3");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn1_JF017_S2_RH;
    public javax.swing.JButton Btn1_JF017_S2_RH1;
    public javax.swing.JButton Btn2_JF017_S2_RH;
    public javax.swing.JButton Btn2_JF017_S2_RH1;
    public javax.swing.JPanel JPSolicitud_JP017_S2_RH;
    public javax.swing.JPanel JPSolicitud_JP017_S2_RH1;
    public javax.swing.JLabel JlLogo;
    public javax.swing.JLabel JlLogo1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
